services:
  postgres:
    image: postgres:16-alpine
    container_name: rental_car_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rental_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rental_db_password}
      POSTGRES_DB: ${POSTGRES_DB:-rental_car_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
